import react from "react";
import { StyleSheet, Text, TextStyle, View, ViewStyle } from "react-native";

const styles = StyleSheet.create({
  
    discoverCoursesText: {
      //position: "absolute",
      //top: 61,
      //left: 30,
      fontSize: 20,
      fontWeight: "600",
      // fontFamily: "Josefin Sans",
      color: "#020000",
      textAlign: "left",
    },
    rectangleView: {
      position: "absolute",
      top: 96,
      left: 30,
      borderRadius: 10,
      backgroundColor: "#f9f9f9",
      width: 360,
      height: 45,
    },
    frameIcon: {
      position: "absolute",
      top: 110,
      left: 41,
      width: 18,
      height: 18,
      overflow: "hidden",
    },
    searchCoursesText: {
      position: "absolute",
      top: 113,
      left: 67,
      fontSize: 15,
      fontWeight: "600",
      // fontFamily: "Josefin Sans",
      color: "#555",
      textAlign: "left",
      width: 157,
      height: 13,
    },
    maskGroupIcon: {
      position: "absolute",
      top: 0,
      left: 0,
      width: 166,
      height: 121,
    },
    stockMarketTerms: {
      position: "absolute",
      top: 101,
      left: 12,
      ffontSize: 15,
      fontWeight: "600",
      // fontFamily: "Josefin Sans",
      color: "#fff",
      textAlign: "left",
    },
    block2View: {
      position: "absolute",
      top: 308,
      left: 224,
      width: 166,
      height: 121,
    },
    maskGroupIcon1: {
      position: "absolute",
      top: 0,
      left: 0,
      width: 360,
      height: 121,
    },
    introToInvesting: {
      position: "absolute",
      top: 98,
      left: 18,
      fontSize: 15,
      fontWeight: "600",
      // fontFamily: "Josefin Sans",
      color: "#fff",
      textAlign: "left",
    },
    block1View: {
      position: "absolute",
      top: 169,
      left: 30,
      width: 360,
      height: 121,
      
    },
    maskGroupIcon2: {
      position: "absolute",
      top: 0,
      left: 0,
      width: 174,
      height: 121,
    },
    whatIsA401k: {
      position: "absolute",
      top: 99,
      left: 12,
      fontSize: 15,
      fontWeight: "600",
      // fontFamily: "Josefin Sans",
      color: "#fff",
      textAlign: "left",
    },
    groupView: {
      position: "absolute",
      top: 308,
      left: 30,
      width: 174,
      height: 121,
    },
    maskGroupIcon3: {
      position: "absolute",
      top: 0,
      left: 0,
      width: 166,
      height: 121,
    },
    bullishVsBearishMarkets: {
      position: "absolute",
      top: 106,
      left: 12,
      fontSize: 15,
      fontWeight: "600",
      // fontFamily: "Josefin Sans",
      color: "#fff",
      textAlign: "left",
    },
    groupView1: {
      position: "absolute",
      top: 448,
      left: 224,
      width: 166,
      height: 121,
    },
    maskGroupIcon4: {
      position: "absolute",
      top: 0,
      left: 0,
      width: 174,
      height: 121,
    },
    whatAreRothIRAs: {
      position: "absolute",
      top: 103,
      left: 9,
      fontSize: 15,
      fontWeight: "600",
      // fontFamily: "Josefin Sans",
      color: "#fff",
      textAlign: "left",
    },
    groupView2: {
      position: "absolute",
      top: 448,
      left: 30,
      width: 174,
      height: 121,
    },
    maskGroupIcon5: {
      position: "absolute",
      top: 0,
      left: 0,
      width: 174,
      height: 121,
    },
    whatIsDiversification: {
      position: "absolute",
      top: 102,
      left: 12,
      fontSize: 15,
      fontWeight: "600",
      // fontFamily: "Josefin Sans",
      color: "#fff",
      textAlign: "left",
    },
    groupView3: {
      position: "absolute",
      top: 587,
      left: 30,
      width: 174,
      height: 121,
    },
    maskGroupIcon6: {
      position: "absolute",
      top: 0,
      left: 0,
      width: 166,
      height: 121,
    },
    whatIsDollarCostAveraging: {
      position: "absolute",
      top: 103,
      left: 8,
      fontSize: 15,
      fontWeight: "600",
      // fontFamily: "Josefin Sans",
      color: "#fff",
      textAlign: "left",
    },
    groupView4: {
      position: "absolute",
      top: 587,
      left: 224,
      width: 166,
      height: 121,
    },
    discoverCoursesView: {
      position: "relative",
      borderRadius: 10,
      backgroundColor: "#fff",
      flex: 1,
      width: "100%",
      height: 750,
      overflow: "hidden",
    },
    container: {
      flex: 1,
      padding: 16,
      backgroundColor: "#ffffff",
    },
    rows: {
      flex: 0,
      padding: 16,
      backgroundColor: "#ffffff",
    },
  });

  export { styles }